[package]
name = "nelder_mead"
version = "0.1.0"
authors = ["João Costa <jdpc557@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Nelder-Mead simplex optimizer"

[dependencies]
rand = "0.6"

[dev-dependencies]
assert_approx_eq = "1.1.0"
